
// This file has been generated by the GUI designer. Do not modify.
namespace Exameer
{
	public partial class PngViewer
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Label lblFilename;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.Table table3;
		
		private global::Gtk.Button btnNextImg;
		
		private global::Gtk.Button btnPrevImg;
		
		private global::Gtk.Button btnResetRectangles;
		
		private global::Gtk.HScale scaleLeftLine;
		
		private global::Gtk.HScale scaleRightLine;
		
		private global::Gtk.DrawingArea drawingarea1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Exameer.PngViewer
			this.Name = "Exameer.PngViewer";
			this.Title = global::Mono.Unix.Catalog.GetString ("PdfViewer");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Exameer.PngViewer.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lblFilename = new global::Gtk.Label ();
			this.lblFilename.Name = "lblFilename";
			this.lblFilename.LabelProp = global::Mono.Unix.Catalog.GetString ("Current File Title");
			this.vbox2.Add (this.lblFilename);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lblFilename]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.table3 = new global::Gtk.Table (((uint)(1)), ((uint)(10)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.btnNextImg = new global::Gtk.Button ();
			this.btnNextImg.CanFocus = true;
			this.btnNextImg.Name = "btnNextImg";
			this.btnNextImg.UseUnderline = true;
			this.btnNextImg.Label = global::Mono.Unix.Catalog.GetString ("Next");
			global::Gtk.Image w2 = new global::Gtk.Image ();
			w2.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-forward", global::Gtk.IconSize.Button);
			this.btnNextImg.Image = w2;
			this.table3.Add (this.btnNextImg);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table3 [this.btnNextImg]));
			w3.LeftAttach = ((uint)(9));
			w3.RightAttach = ((uint)(10));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.btnPrevImg = new global::Gtk.Button ();
			this.btnPrevImg.CanFocus = true;
			this.btnPrevImg.Name = "btnPrevImg";
			this.btnPrevImg.UseUnderline = true;
			this.btnPrevImg.Label = "Previous";
			global::Gtk.Image w4 = new global::Gtk.Image ();
			w4.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-back", global::Gtk.IconSize.Button);
			this.btnPrevImg.Image = w4;
			this.table3.Add (this.btnPrevImg);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table3 [this.btnPrevImg]));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.btnResetRectangles = new global::Gtk.Button ();
			this.btnResetRectangles.CanFocus = true;
			this.btnResetRectangles.Name = "btnResetRectangles";
			this.btnResetRectangles.UseUnderline = true;
			this.btnResetRectangles.Label = global::Mono.Unix.Catalog.GetString ("Reset");
			global::Gtk.Image w6 = new global::Gtk.Image ();
			w6.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-cancel", global::Gtk.IconSize.Button);
			this.btnResetRectangles.Image = w6;
			this.table3.Add (this.btnResetRectangles);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table3 [this.btnResetRectangles]));
			w7.LeftAttach = ((uint)(4));
			w7.RightAttach = ((uint)(5));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox4.Add (this.table3);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.table3]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.scaleLeftLine = new global::Gtk.HScale (null);
			this.scaleLeftLine.CanFocus = true;
			this.scaleLeftLine.Name = "scaleLeftLine";
			this.scaleLeftLine.Adjustment.Upper = 100;
			this.scaleLeftLine.Adjustment.PageIncrement = 5;
			this.scaleLeftLine.Adjustment.StepIncrement = 0.5;
			this.scaleLeftLine.Adjustment.Value = 25;
			this.scaleLeftLine.DrawValue = true;
			this.scaleLeftLine.Digits = 2;
			this.scaleLeftLine.ValuePos = ((global::Gtk.PositionType)(0));
			this.vbox4.Add (this.scaleLeftLine);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.scaleLeftLine]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.scaleRightLine = new global::Gtk.HScale (null);
			this.scaleRightLine.CanFocus = true;
			this.scaleRightLine.Name = "scaleRightLine";
			this.scaleRightLine.Adjustment.Upper = 100;
			this.scaleRightLine.Adjustment.PageIncrement = 5;
			this.scaleRightLine.Adjustment.StepIncrement = 0.5;
			this.scaleRightLine.Adjustment.Value = 75.19;
			this.scaleRightLine.DrawValue = true;
			this.scaleRightLine.Digits = 2;
			this.scaleRightLine.ValuePos = ((global::Gtk.PositionType)(0));
			this.vbox4.Add (this.scaleRightLine);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.scaleRightLine]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			this.vbox3.Add (this.vbox4);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.vbox4]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.drawingarea1 = new global::Gtk.DrawingArea ();
			this.drawingarea1.Name = "drawingarea1";
			this.vbox3.Add (this.drawingarea1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.drawingarea1]));
			w12.Position = 2;
			w12.Padding = ((uint)(10));
			this.vbox2.Add (this.vbox3);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox3]));
			w13.Position = 1;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 708;
			this.DefaultHeight = 299;
			this.Show ();
			this.SizeAllocated += new global::Gtk.SizeAllocatedHandler (this.OnSizeAllocated);
			this.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler (this.OnKeyReleaseEvent);
			this.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.OnKeyPressEvent);
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.btnResetRectangles.Clicked += new global::System.EventHandler (this.OnBtnResetRectanglesClicked);
			this.btnPrevImg.Clicked += new global::System.EventHandler (this.OnBtnPrevImgClicked);
			this.btnNextImg.Clicked += new global::System.EventHandler (this.OnBtnNextImgClicked);
			this.scaleLeftLine.ValueChanged += new global::System.EventHandler (this.OnScaleLeftLineValueChanged);
			this.scaleRightLine.ValueChanged += new global::System.EventHandler (this.OnScaleRightLineValueChanged);
		}
	}
}
